repository_type: pipeline
lint:
  actions_ci: false
  files_unchanged:
    - assets/email_template.html
    - assets/email_template.txt
    - .gitignore
    - .github/PULL_REQUEST_TEMPLATE.md
  files_exist:
    - conf/modules.config
  nextflow_config:
    - config_defaults:
        - params.ribo_database_manifest
