repository_type: pipeline
lint:
  files_unchanged:
    - assets/email_template.html
    - assets/email_template.txt
  files_exist:
    - conf/modules.config
  nextflow_config:
    - config_defaults:
        - params.ribo_database_manifest
